name: Deploy to EKS Cluster

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to create"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Check Pre-installed AWS CLI
    - name: Check Pre-installed AWS CLI
      run: |
        aws --version || echo "AWS CLI not found"

    # Step 4: Install or Update AWS CLI
    - name: Install or Update AWS CLI
      run: |
        set -x
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install --update
        aws --version

    # Step 5: Test AWS CLI
    - name: Test AWS CLI
      run: |
        aws sts get-caller-identity

    # Step 6: Update kubeconfig for EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name test-kube

    # Step 7: Apply Namespace and Resource Quota
    - name: Apply Namespace and Resource Quota
      run: |
        kubectl create namespace ${{ github.event.inputs.namespace }} || true
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: tenant-quota
          namespace: ${{ github.event.inputs.namespace }}
        spec:
          hard:
            pods: "10"
            requests.cpu: "2"
            requests.memory: "4Gi"
            limits.cpu: "4"
            limits.memory: "8Gi"
        EOF

    # Step 8: Verify Namespace and Quota
    - name: Verify Namespace and Quota
      run: |
        kubectl get namespaces
        kubectl describe resourcequota tenant-quota -n ${{ github.event.inputs.namespace }}
