name: Deploy to EKS Cluster

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to create"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    # Step 4: Install AWS CLI using apt
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
        aws --version

    # Step 5: Update kubeconfig to point to your EKS cluster
    - name: Update kubeconfig for EKS cluster
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name test-kube

    # Step 6: Apply Namespace and Resource Quotas
    - name: Apply Namespace and Resource Quota
      run: |
        kubectl create namespace ${{ github.event.inputs.namespace }} || true
        kubectl apply -f - <<EOF
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: tenant-quota
          namespace: ${{ github.event.inputs.namespace }}
        spec:
          hard:
            pods: "10"
            requests.cpu: "2"
            requests.memory: "4Gi"
            limits.cpu: "4"
            limits.memory: "8Gi"
        EOF

    # Step 7: Verify Deployment
    - name: Verify Namespace and Quota
      run: |
        kubectl get namespaces
        kubectl describe resourcequota tenant-quota -n ${{ github.event.inputs.namespace }}
